import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dbConnect from "@/lib/db";
import { AlertDialog, AlertDialogContent } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { getSetting } from "@/actions";
import { z } from "zod";
import ApiKeyPrompt from "./(components)/ApiKeyPrompt";
import Navbar from "./(components)/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  const apiKeySet = (await getSetting("api_key")) !== null;

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen py-2 w-screen bg-neutral-900 text-neutral-100 overflow-hidden h-screen">
          <div className="max-w-[1600px] place-self-center w-full max-h-[90%]">
            {!apiKeySet && <ApiKeyPrompt />}
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
